defmodule WavelinkWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :wavelink

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_wavelink_key",
    signing_salt: "fMtIYY8W",
    same_site: "Lax"
  ]

  socket "/socket", WavelinkWeb.UserSocket,
    websocket: [check_origin: {WavelinkWeb.Endpoint, :origin_allowed?, []}],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :wavelink,
    gzip: not code_reloading?,
    only: WavelinkWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Ahead of the router, not inside its :api pipeline — an OPTIONS
  # preflight is for a path/method the router never defines (only POST
  # /api/register and the /api/conversations routes exist), so a plug
  # living inside routing would 404 before ever getting a chance to answer
  # the preflight.
  #
  # `headers:` adds x-user-id to CORSPlug's default allowlist — without it
  # the browser accepts the preflight but then silently blocks the actual
  # request, since x-user-id (see WavelinkWeb.Plugs.RequireUserId) isn't
  # one of the "simple" headers CORS allows unless a server opts in.
  plug CORSPlug,
    origin: &WavelinkWeb.Endpoint.cors_origins/0,
    headers: CORSPlug.defaults()[:headers] ++ ["x-user-id"]

  plug WavelinkWeb.Router

  @doc false
  # MFA form of `check_origin` — Phoenix calls this with the connecting
  # client's parsed origin URI and wants a boolean back. The allowed list
  # itself is per-env config (see config/*.exs): dev allows the Vite dev
  # server, prod allows only the deployed demo UI's origin.
  def origin_allowed?(%URI{scheme: scheme, host: host, port: port}) do
    allowed = Application.get_env(:wavelink, :allowed_origins, [])

    Enum.any?(allowed, fn origin ->
      case URI.parse(origin) do
        %URI{scheme: ^scheme, host: ^host, port: ^port} -> true
        _ -> false
      end
    end)
  end

  @doc false
  # MFA form CORSPlug expects: just the raw list of allowed origins.
  def cors_origins do
    Application.get_env(:wavelink, :allowed_origins, [])
  end
end
