import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :wavelink, WavelinkWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Le7xkYbPYx2dtdBgk//TczTzLy+bB2ZhfMaumHJPx4hT+li2A9lJD2VltUPmhb8O",
  watchers: []

# In-memory store — no AWS credentials needed for local dev. Swapped for
# Wavelink.Store.Dynamo in prod, see config/runtime.exs.
config :wavelink, :store, Wavelink.Store.Memory
config :wavelink, :directory, Wavelink.Directory.Memory
config :wavelink, :conversations, Wavelink.Conversations.Memory

# The Vite dev server's origin. Real check_origin enforcement happens via
# the socket's own MFA (see endpoint.ex); the top-level `check_origin: false`
# above only covers non-socket requests.
config :wavelink, :allowed_origins, ["http://localhost:5173"]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :wavelink, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
